### PR TITLE
Added solution for challenge 4

### PR DESCRIPTION
**Pull request by msvamp**
Solution for challenge 4

Signed-off-by: Manas Sambhus

P.S.  Not tested extensively
(This is my first program in Lua and Code Forces doesn't support Lua 😭)

### CODE REVIEW

**Review by AsianIntel — APPROVED** [review]
Works for the sample cases given lol

**Comment by aniket1020** [comment]
I have no clue about this code

**Review by aniket1020 — APPROVED** [review]
I have no idea about this code xdd

**Comment by msvamp** [comment]
So, no one willing to merge? 😴

**Pull request merged**
